sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jerrypicking/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jerrypicking/react-test npm test -- --coverage
  # you can add a new test here
after_success:
  - docker build -t jerrypicking/multi-client ./client
  - docker build -t jerrypicking/multi-nginx ./nginx
  - docker build -t jerrypicking/multi-server ./server
  - docker build -t jerrypicking/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jerrypicking/multi-client
  - docker push jerrypicking/multi-nginx
  - docker push jerrypicking/multi-server
  - docker push jerrypicking/multi-worker